#!/usr/bin/python
#usage: ./generate_input_xml [source xml file name]
import sys
import logging
import os.path

from tester import generate_test_xml

EXIT_CODE_INCORRECT_ARGUMENTS = 1

def main():
    # configure logger
    global log
    log = logging.getLogger("main")
    formatter = logging.Formatter('%(name)s %(levelname)s: %(message)s')
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(formatter)
    log.addHandler(handler)
    log.setLevel(logging.WARNING)

    if len(sys.argv)!=2:
        log.critical("Incorrect usage - invalid number of arguments! Make sure that options come before argument.\n" + __doc__)
        sys.exit(EXIT_CODE_INCORRECT_ARGUMENTS)

    pkg_name=sys.argv[-1]
    xml_file_name=pkg_name+".xml"
    if os.path.islink(xml_file_name):
        xml_file_name=os.path.realpath(xml_file_name)
    # address is hard coded to the same value for now. But it shouldn't matter
    generate_test_xml(pkg_name,"0x17000000",xml_file_name,"test.xml")


if __name__ == '__main__':
    main()
